info:
  version: 1.0.2
  description: NSSF initial local configuration

configuration:
  nssfName: NSSF # the name of this NSSF
  sbi: # Service-based interface information
    scheme: http # the protocol for sbi (http or https)
    registerIPv4: nssf.free5gc.org # IP used to register to NRF
    bindingIPv4: nssf.free5gc.org  # IP used to bind the service
    port: 8000 # Port used to bind the service
    tls: # the local path of TLS key
      pem: cert/nssf.pem # NSSF TLS Certificate
      key: cert/nssf.key # NSSF TLS Private key
  serviceNameList: # the SBI services provided by this SMF, refer to TS 29.531
    - nnssf-nsselection # Nnssf_NSSelection service
    - nnssf-nssaiavailability # Nnssf_NSSAIAvailability service
  nrfUri: http://nrf.free5gc.org:8000 # a valid URI of NRF
  nrfCertPem: cert/nrf.pem
  supportedPlmnList: # the PLMNs (Public land mobile network) list supported by this NSSF
    - mcc: 001 # Mobile Country Code (3 digits string, digit: 0~9)
      mnc: 01 # Mobile Network Code (2 or 3 digits string, digit: 0~9)
  supportedNssaiInPlmnList: # Supported S-NSSAI List for each PLMN
    - plmnId: # Public Land Mobile Network ID, <PLMN ID> = <MCC><MNC>
        mcc: 001 # Mobile Country Code (3 digits string, digit: 0~9)
        mnc: 01 # Mobile Network Code (2 or 3 digits string, digit: 0~9)
      supportedSnssaiList: # Supported S-NSSAIs of the PLMN
        - sst: 1 # Slice/Service Type (uinteger, range: 0~255)
          sd: 000001 # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
        - sst: 1 # Slice/Service Type (uinteger, range: 0~255)
          sd: 000002 # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
  nsiList: # List of available Network Slice Instance (NSI)
    - snssai: # S-NSSAI of this NSI
        sst: 1 # Slice/Service Type (uinteger, range: 0~255)
        sd: 000001 # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
      nsiInformationList: # Information list of this NSI
        # the NRF to be used to select the NFs/services within the selected NSI, and an optonal ID
        - nrfId: http://nrf.free5gc.org:8000/nnrf-nfm/v1/nf-instances
          nsiId: 1
    - snssai: # S-NSSAI of this NSI
        sst: 1 # Slice/Service Type (uinteger, range: 0~255)
        sd: 000002 # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
      nsiInformationList: # Information list of this NSI
        # the NRF to be used to select the NFs/services within the selected NSI, and an optonal ID
        - nrfId: http://nrf.free5gc.org:8000/nnrf-nfm/v1/nf-instances
          nsiId: 2
  amfSetList: # List of AMF Sets that my be assigned by this NSSF
    - amfSetId: 1 # the AMF Set identifier
      amfList:
      # URI of the NRF used to determine the list of candidate AMF(s) from the AMF Set
      nrfAmfSet: http://nrf.free5gc.org:8000/nnrf-nfm/v1/nf-instances
      # the Nssai availability data information per TA supported by the AMF
      supportedNssaiAvailabilityData:
        - tai: # Tracking Area Identifier
            plmnId: # Public Land Mobile Network ID, <PLMN ID> = <MCC><MNC>
              mcc: 001 # Mobile Country Code (3 digits string, digit: 0~9)
              mnc: 01 # Mobile Network Code (2 or 3 digits string, digit: 0~9)
            tac: 1 # Tracking Area Code (uinteger, range: 0~16777215)
          supportedSnssaiList: # Supported S-NSSAIs of the tracking area
            - sst: 1 # Slice/Service Type (uinteger, range: 0~255)
              sd: 000001 # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
            - sst: 1 # Slice/Service Type (uinteger, range: 0~255)
              sd: 000002 # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
  taList: # List of supported tracking area and their related information of this NSSF instance
    - tai: # Tracking Area Identity
        plmnId: # Public Land Mobile Network ID, <PLMN ID> = <MCC><MNC>
          mcc: 001 # Mobile Country Code (3 digits string, digit: 0~9)
          mnc: 01 # Mobile Network Code (2 or 3 digits string, digit: 0~9)
        tac: 1 # Tracking Area Code (uinteger, range: 0~16777215)
      accessType: 3GPP_ACCESS # Access type of the tracking area
      supportedSnssaiList: # List of supported S-NSSAIs of the tracking area
        - sst: 1 # Slice/Service Type (uinteger, range: 0~255)
          sd: 000001 # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
        - sst: 1 # Slice/Service Type (uinteger, range: 0~255)
          sd: 000002 # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
  # List of mappings of S-NSSAI in the serving network and the value of the home network

  # Metrics configuration
  # If using the same bindingIPv4 as the sbi server, make sure that the ports are different
  metrics:
    enable: false # (Optional, default false)
    scheme: http # (Required) the protocol for metrics (http or https, default https)
    bindingIPv4: nssf.free5gc.org # (Required) IP used to bind the metrics endpoint (default 0.0.0.0)
    port: 9091 # (Optional, default 9091) port used to bind the service
    tls: # (Optional) the local path of TLS key (Could be the same as the sbi ones)
      pem: cert/nssf.pem # NSSF TLS Certificate
      key: cert/nssf.key # NSSF TLS Private key
    namespace: free5gc # (Optional, default free5gc)

logger: # log output setting
  enable: true # true or false
  level: info # how detailed to output, value: trace, debug, info, warn, error, fatal, panic
  reportCaller: false # enable the caller report or not, value: true or false
